---
apiVersion: v1
data:
  secretword: c2VjcmV0d29yZCBmcm9tIGs4cyBzZWNyZXQK
  evanli_db_username: ZXZhbmxpdXNlcg==
  evanli_db_password: ZXZhbmxpcGFzc3dvcmQ=
  evanli_db_database: ZXZhbmxp
  evanli_db_jdbcurl: amRiYzpwb3N0Z3Jlc3FsOi8vZXZhbmxpLXBvc3RncmVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9ldmFubGk=
  jwt_secret: NU50MCQ1MVhpNnVACg==
  evanli_host: aHR0cDovLzE0Ni4xODUuMjQzLjkw
kind: Secret
metadata:
  name: evanlisecrets
  namespace: default
type: Opaque