version: "3"
services:
  usersdb:
    container_name: usersdb
    image: library/postgres:14.5
    environment:
      POSTGRES_USER: evanliuser
      POSTGRES_PASSWORD: evanlipassword
      POSTGRES_DB: evanli
    networks:
      - backend
    ports:
      - 5432:5432

networks:
  frontend:
  backend: