
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: usersuser
    password: userspassword
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

liquibase:
  enabled: true
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/users
  user: usersuser
  password: userspassword
