
docker-build:
	docker build -t eshurupov/evanli-transactions:1.0 -t eshurupov/evanli-transactions:latest .

docker-login:
	docker login

docker-push:
	docker push --all-tags eshurupov/evanli-transactions